version = 1

# Project name
name = "freakme.fun"

# Enable analyzers
[[analyzers]]
name = "javascript"
enabled = true

[analyzers.meta]
runtime_version = "18.x" # Match your Node.js version (Next.js default is 18+)
environment = ["browser", "jest", "nodejs"]
module_system = "es-modules"
dialect = "typescript"

# Enable experimental AI features
[analyzers.config]
experimental = true
dependency_analysis = true
style_guide = true
performance = true
security = true

# Exclude paths (build artifacts, config, etc.)
exclude_paths = [
  "node_modules/",
  ".next/",
  "dist/",
  "public/static/",
  ".vercel/",
  "**/*.d.ts",
  "**/*.test.{js,jsx,ts,tsx}",
  "**/__mocks__/",
  "coverage/"
]

# Include paths you want scanned
include_paths = [
  "src/",
  "components/",
  "pages/",
  "lib/",
  "utils/",
  "hooks/",
  "contexts/",
  "api/"
]

# Configuration for issues you want ignored
[[analyzers.ignored_issues]]
code = "JS-0346" # Ignore missing PropTypes in React
path = "**/*.tsx"

[[analyzers.ignored_issues]]
code = "JS-0002" # Ignore unused variables in test files
path = "**/*.test.{js,jsx,ts,tsx}"

# Enable security scanner with enhanced settings
[[analyzers]]
name = "security"
enabled = true

[analyzers.meta]
vulnerability_detection = "high"

# Enable Python analyzer for backend code
[[analyzers]]
name = "python"
enabled = true

[analyzers.meta]
runtime_version = "3.11"

# Enable secrets scanner
[[analyzers]]
name = "secrets"
enabled = true

# Enable Docker analyzer
[[analyzers]]
name = "docker"
enabled = true

# CI integration setup
[ci]
upload = true
fail_on_severity = "high"

# Repository settings
[repository]
branch = "main"
provider = "github"

# Transformers for automatic fixes
[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "black"
enabled = true

# Custom issue severity overrides
[[issue_overrides]]
code = "SEC-0001" # Example: Hardcoded secrets
severity = "critical"

[[issue_overrides]]
code = "SEC-0002" # Example: SQL injection
severity = "critical"
